### ISSUE TITLE
Change label used for current `-dev` builds to `-alpha`

### ISSUE THREAD

**Issue by CharliePoole** [nunit/NUnit.Cake.Recipe#41]
Whenever a build is merged to the main or version4 branch, the packages are published to our MyGet feed using the "dev" pre-release label. This presents a bit of a problem, since "dev" alphabetically follows "alpha" and "beta" but is intended to precede them logically. It also causes extra work, since outdated releases must be deleted manually from the feed to prevent using them accidentally.

We will resolve this by using `alpha` in place of `dev`.  This will make the MyGet builds a sort of running alpha, with many such releases before we move to either `beta` or to a final release.

Individual projects using the recipe will only be affected when they update to a version of the recipe in which this change appears.

**Comment by OsirisTerje** [comment]
Just for info:  NUnit framework is using the same approach.  -alpha versions go to Myget,  beta and release to nuget.

**Comment by CharliePoole** [comment]
I haven't changed where the builds are going, so I should check that. I don't want multiple alphas per day going to nuget!

**Comment by CharliePoole** [comment]
Note that the recipe is used to build the recipe package itself so it is now using alpha the myget feed.
