### ISSUE TITLE
Replace deprecated NoCache option when installing nuget packages

### ISSUE THREAD

**Issue by CharliePoole** [nunit/NUnit.Cake.Recipe#45]
Replace it with NoHttpCache

**Comment by mikkelbu** [comment]
I also noticed this when reviewing #44 . As far as I can tell we cannot do much about it as Cake does not support this yet. I've created a bug-report for them - see #4412

**Comment by CharliePoole** [comment]
@mikkelbu Cake provides a way to pass extra arguments to the underlying tool. see [Argument Customization](https://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/50AAB3A8)
