### ISSUE TITLE
Appveyor build not triggered

### ISSUE THREAD

**Issue by CharliePoole** [nunit/NUnit.Cake.Recipe#8]
Currently, it's only possible to manually kick off builds of main on AppVeyor. It's possible that the web hook is not set up correctly.

**Comment by CharliePoole** [comment]
@CharliePoole @veleek 

I'm thinking of closing this and just dropping the AppVeyor build...

1. It has never worked well for the recipe. This is also the case for my TestCentric recipe.
2. If GitHub actions don't work, it's probably because GitHub is down, so no CI will work anyway.
3. I imagine that the recipe will be maintained by only one or two people, who can use their local machine to
   publish changes to MyGet, NuGet and Chocolatey as a backup.

Thoughts? Would this logic also apply to the console runner?

**Comment by veleek** [comment]
I see no issues removing the AppVeyor stuff.  It's just another thing we need to manage permissions on.
